# Generated by Django 5.2.7 on 2025-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='Descripción breve')),
                ('categoria', models.CharField(max_length=100)),
                ('anio_publicacion', models.PositiveIntegerField(verbose_name='Año de publicación')),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
