# Generated by Django 5.2.8 on 2025-11-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Portada del Libro'),
        ),
    ]
